package com.maxieds.chameleonminiusb;

import com.maxieds.chameleonminiusb.ChameleonDeviceConfig.ChameleonBoardType_t;
import com.maxieds.chameleonminiusb.ChameleonDeviceConfig.ChameleonEmulatedConfigType_t;
import com.maxieds.chameleonminiusb.LibraryLogging.LocalLoggingLevel;

interface ChameleonUSBInterface {

    /** Initialize the Chameleon USB library.
     * @return truth value of whether the initialization operation was successful.
     */
    boolean chameleonUSBInterfaceInitialize();

    /**
     * Call one of these functions to initialize the Chameleon USB library.
     * @param libraryLoggingLevel : level of detail in logging events and data generated by the library.
     * @return truth value of whether the initialization operation was successful.
     */
    boolean chameleonUSBInterfaceInitialize(LocalLoggingLevel libraryLoggingLevel);

    /**
     * Tests for whether
     * @return
     */
    boolean chameleonPresent();
    boolean chameleonPresent(ChameleonBoardType_t expectedRevType);

    boolean chameleonLoad(byte[] tagDataBytes, ChameleonEmulatedConfigType_t chameleonConfigType);
    boolean chameleonLoad(byte[] tagDataBytes, ChameleonEmulatedConfigType_t chameleonConfigType,
                          int slotNumber, boolean clearSlotBeforeLoading);

}

