package com.maxieds.chameleonminiusb;

import android.content.Intent;

public interface ChameleonLibraryLoggingReceiver {

    /**
     * This method should be overridden in an interface implementation to handle real-time
     * processing of logs generated by the library at runtime and throughout its
     * lifecycle in a third-party application.
     * @param logEntry : the newly generated logging information.
     */
    void onReceiveNewLoggingData(Intent logEntryIntent);

}
